import { build } from 'esbuild';
import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
// A classic script also runs when index.html is opened directly with file://.
await build({
  absWorkingDir: root,
  entryPoints: ['app.js'],
  outfile: 'app.bundle.js',
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: ['chrome100', 'firefox100', 'safari15.4'],
  banner: { js: '// Generated by npm run build. Edit the source modules, then rebuild.' },
  logLevel: 'info',
});

// GitHub Pages lets browsers cache files for hours; version the references so a
// new release is loaded at once.
let html = await readFile(`${root}index.html`, 'utf8');
for (const file of ['styles.css', 'app.bundle.js', 'assets/jszip.min.js']) {
  const hash = createHash('sha256').update(await readFile(`${root}${file}`)).digest('hex').slice(0, 10);
  html = html.replace(new RegExp(`(["'])${file.replace(/[.]/g, '\\.')}(\\?v=[\\w]+)?\\1`, 'g'), `$1${file}?v=${hash}$1`);
}
await writeFile(`${root}index.html`, html);
